export const POSTHOG_EVENTS = {
  town_closed: "town_closed",
  town_opened: "town_opened",
  trainer_card_opened: "trainer_card_opened",
  trainer_card_closed: "trainer_card_closed",
  spotify_song_opened: "spotify_song_opened",
  spotify_song_closed: "spotify_song_closed",
  google_books_opened: "google_books_opened",
  google_books_closed: "google_books_closed",
  pokemon_ball_opened: "pokemon_ball_opened",
  pokemon_ball_closed: "pokemon_ball_closed",
  resume_opened: "resume_opened",
  resume_closed: "resume_closed",
  github_link_clicked: "github_link_clicked",
  linkedin_link_clicked: "linkedin_link_clicked",
  cookie_banner_dismissed: "cookie_banner_dismissed",
  privacy_policy_opened: "privacy_policy_opened",
  privacy_policy_closed: "privacy_policy_closed",
  spotify_open_in_spotify_clicked: "spotify_open_in_spotify_clicked",
  view_source_code_clicked: "view_source_code_clicked",
} as const;
