export const TEST_IDS = {
  homeScreen: "home-screen",
  townMap: "town-map",
  bottomBar: "bottom-bar",
  townChicago: "town-chicago",
  townNotreDame: "town-notre-dame",
  townFierySpirit: "town-fiery-spirit",
  townModalChicago: "town-modal-chicago",
  townModalNotreDame: "town-modal-notre-dame",
  townModalFierySpirit: "town-modal-fiery-spirit",
  trainerCardModal: "trainer-card-modal",
  trainerCardClose: "trainer-card-close",
  spotifyModal: "spotify-modal",
  googleBooksModal: "google-books-modal",
} as const;
